title: "Origin 解体新書"
summary: "Web 技術解体新書\n第一章 Origin 解体新書\n現在の Web における最も重要なセキュリティモデルの 1 つである Origin について、この概念が持ち込まれた背景やそれがユーザを保護するメカニズム、 JSONP などで迂回した場合の危険性と CORS による安全な拡張、 Preflight が飛ぶ理由、 Service Worker など新しい API との連携、 Spectre によって発覚した脆弱性と CORP,COOP,COEP, Origin Isolation まで、関連知識を体系的に解説する。"
topics: ["origin", "web"]
published: false
price: 0
